// backend/backend-node/seed.js
// Run once: node seed.js
// Seeds doctors and admin into MongoDB

import { MongoClient } from "mongodb";
import dotenv from "dotenv";
dotenv.config();

const client = new MongoClient(process.env.MONGO_URI || "mongodb://localhost:27017/");
await client.connect();
const db = client.db("hospital_system");

// ── Clear existing ──────────────────────────────────────
await db.collection("doctors").deleteMany({});
await db.collection("admins").deleteMany({});

// ── Seed Doctors ────────────────────────────────────────
await db.collection("doctors").insertMany([
  { doctorId:"D200", name:"Dr. Asha Reddy",   specialization:"Radiology",       departments:"Radiology, General Medicine, Orthopedics, Endocrinology, Cardiology", hospital:"Lotus MultiSpeciality Hospital", experience:"26", qualification:"MD Radiology, FRCR",         password:"pass200!" },
  { doctorId:"D201", name:"Dr. Ravi Kumar",   specialization:"Neurology",        departments:"Neurology, Radiology, Psychiatry, Pulmonology, Gastroenterology",     hospital:"CityCare Medical Centre",        experience:"5",  qualification:"MD Neurology, DM",            password:"pass201!" },
  { doctorId:"D202", name:"Dr. Neha Sharma",  specialization:"General Medicine", departments:"General Medicine, Pulmonology, Cardiology, Gastroenterology, Neurology", hospital:"Prima Diagnostic & Care",     experience:"27", qualification:"MBBS, MD General Medicine, DNB", password:"pass202!" },
  { doctorId:"D203", name:"Dr. Kiran Rao",    specialization:"Endocrinology",    departments:"Endocrinology, Neurology, Psychiatry, Radiology, Cardiology",         hospital:"RiverSide Healthcare",           experience:"16", qualification:"MD Endocrinology, DM, FACE",  password:"pass203!" },
  { doctorId:"D204", name:"Dr. Suresh Patel", specialization:"Nephrology",       departments:"Nephrology, Psychiatry, Neurology, Radiology, Cardiology",            hospital:"Prima Diagnostic & Care",        experience:"22", qualification:"MD Nephrology, DM, FASN",     password:"pass204!" },
]);
console.log("✅ Doctors seeded");

// ── Seed Admin ──────────────────────────────────────────
await db.collection("admins").insertOne({
  adminId: "admin001",
  name: "Hospital Admin",
  password: "admin123",
  role: "admin",
});
console.log("✅ Admin seeded");

// ── Seed Patients (from CSV data) ───────────────────────
await db.collection("patients").deleteMany({});
await db.collection("patients").insertMany([
  { userId:"P300", name:"Sanjay",   surname:"Reddy",  email:"sanjay.reddy@email.com",   password:"pass300", age:"9",  gender:"M", hospital:"CityCare Medical Centre",        hosp_address:"MG Road, Secunderabad",          hosp_phone:"+91-9219540831", disease:"Pneumonia",              status:"Under Treatment", medicines:"Ceftriaxone, Clopidogrel, Omeprazole, Atorvastatin", procedures:"Endoscopy",                                   doctor:"Dr. Ravi Kumar",   doctor_id:"D201", appointment:"2025-12-19", next_appointment:"2026-03-04", lab:"CBC: Hb 14.9 g/dL | Blood Glucose: 288 mg/dL | Urine: Pus Cells+" },
  { userId:"P301", name:"Shreya",   surname:"Gupta",  email:"shreya.gupta@email.com",   password:"pass301", age:"21", gender:"F", hospital:"RiverSide Healthcare",            hosp_address:"Hitech City, Hyderabad",         hosp_phone:"+91-9896233790", disease:"Type 2 Diabetes",        status:"Under Treatment", medicines:"Furosemide",                                         procedures:"Dialysis Session",                            doctor:"Dr. Kiran Rao",    doctor_id:"D203", appointment:"2025-08-03", next_appointment:"2025-09-29", lab:"CBC: Hb 14.9 g/dL | Blood Glucose: 233 mg/dL | Urine: Pus Cells+" },
  { userId:"P302", name:"Ritu",     surname:"Chawla", email:"ritu.chawla@email.com",    password:"pass302", age:"19", gender:"F", hospital:"CityCare Medical Centre",        hosp_address:"MG Road, Secunderabad",          hosp_phone:"+91-9219540831", disease:"Hypertension",           status:"Discharged",      medicines:"Metformin, Atorvastatin, Losartan",                  procedures:"Coronary Angiography",                        doctor:"Dr. Kiran Rao",    doctor_id:"D203", appointment:"2025-10-04", next_appointment:"2025-11-29", lab:"CBC: Hb 13.2 g/dL | Blood Glucose: 207 mg/dL | Urine: Blood+" },
  { userId:"P303", name:"Ritu",     surname:"Chawla", email:"ritu.chawla2@email.com",   password:"pass303", age:"77", gender:"F", hospital:"Prima Diagnostic & Care",        hosp_address:"Kukatpally, Hyderabad",          hosp_phone:"+91-9395310485", disease:"Fracture - Radius",      status:"Under Treatment", medicines:"Amoxicillin, Aspirin, Salbutamol",                   procedures:"None",                                        doctor:"Dr. Neha Sharma",  doctor_id:"D202", appointment:"2024-09-26", next_appointment:"2024-12-22", lab:"CBC: Hb 14.8 g/dL | Blood Glucose: 290 mg/dL | Urine: Normal" },
  { userId:"P304", name:"Kavya",    surname:"Menon",  email:"kavya.menon@email.com",    password:"pass304", age:"82", gender:"Other", hospital:"Prima Diagnostic & Care",    hosp_address:"Kukatpally, Hyderabad",          hosp_phone:"+91-9395310485", disease:"Acute Appendicitis",     status:"Discharged",      medicines:"Enoxaparin, Paracetamol, Amoxicillin",               procedures:"None",                                        doctor:"Dr. Suresh Patel", doctor_id:"D204", appointment:"2024-09-03", next_appointment:"2024-09-18", lab:"CBC: Hb 9.1 g/dL | Blood Glucose: 265 mg/dL | Urine: Pus Cells+" },
  { userId:"P305", name:"Arjun",    surname:"Nair",   email:"arjun.nair@email.com",     password:"pass305", age:"17", gender:"M", hospital:"RiverSide Healthcare",            hosp_address:"Hitech City, Hyderabad",         hosp_phone:"+91-9896233790", disease:"Migraine",               status:"Discharged",      medicines:"Salbutamol, Ceftriaxone, Clopidogrel",               procedures:"Physiotherapy Session",                       doctor:"Dr. Suresh Patel", doctor_id:"D204", appointment:"2024-09-10", next_appointment:"2024-12-01", lab:"CBC: Hb 9.9 g/dL | Blood Glucose: 293 mg/dL | Urine: Protein+" },
  { userId:"P306", name:"Priya",    surname:"Reddy",  email:"priya.reddy@email.com",    password:"pass306", age:"30", gender:"Other", hospital:"CityCare Medical Centre",    hosp_address:"MG Road, Secunderabad",          hosp_phone:"+91-9219540831", disease:"Urinary Tract Infection", status:"Admitted",       medicines:"Amoxicillin, Losartan, Metformin",                   procedures:"Laparoscopic Cholecystectomy",                 doctor:"Dr. Ravi Kumar",   doctor_id:"D201", appointment:"2024-05-15", next_appointment:"2024-07-13", lab:"CBC: Hb 8.5 g/dL | Blood Glucose: 231 mg/dL | Urine: Normal" },
  { userId:"P307", name:"Abhishek", surname:"Das",    email:"abhishek.das@email.com",   password:"pass307", age:"13", gender:"M", hospital:"RiverSide Healthcare",            hosp_address:"Hitech City, Hyderabad",         hosp_phone:"+91-9896233790", disease:"Cholelithiasis",         status:"Under Treatment", medicines:"Furosemide, Clopidogrel, Amoxicillin",               procedures:"None",                                        doctor:"Dr. Ravi Kumar",   doctor_id:"D201", appointment:"2025-04-04", next_appointment:"2025-06-09", lab:"CBC: Hb 11.0 g/dL | Blood Glucose: 189 mg/dL | Urine: Normal" },
  { userId:"P308", name:"Ritu",     surname:"Chawla", email:"ritu.chawla3@email.com",   password:"pass308", age:"10", gender:"F", hospital:"Prima Diagnostic & Care",        hosp_address:"Kukatpally, Hyderabad",          hosp_phone:"+91-9395310485", disease:"Ischemic Heart Disease", status:"Admitted",        medicines:"Enoxaparin, Prednisone, Metformin, Salbutamol",      procedures:"None",                                        doctor:"Dr. Kiran Rao",    doctor_id:"D203", appointment:"2025-02-03", next_appointment:"2025-04-22", lab:"CBC: Hb 8.4 g/dL | Blood Glucose: 208 mg/dL | Urine: Normal" },
  { userId:"P309", name:"Rakesh",   surname:"Gupta",  email:"rakesh.gupta@email.com",   password:"pass309", age:"20", gender:"M", hospital:"Lotus MultiSpeciality Hospital", hosp_address:"Banjara Hills, Hyderabad",        hosp_phone:"+91-9126855092", disease:"COPD",                   status:"Discharged",      medicines:"Losartan, Clopidogrel, Prednisone, Atorvastatin",    procedures:"None",                                        doctor:"Dr. Asha Reddy",   doctor_id:"D200", appointment:"2024-03-11", next_appointment:"2024-05-08", lab:"CBC: Hb 14.8 g/dL | Blood Glucose: 218 mg/dL | Urine: Normal" },
  { userId:"P310", name:"Siddharth",surname:"Iyer",   email:"siddharth.iyer@email.com", password:"pass310", age:"73", gender:"M", hospital:"Prima Diagnostic & Care",        hosp_address:"Kukatpally, Hyderabad",          hosp_phone:"+91-9395310485", disease:"Stroke",                 status:"Admitted",        medicines:"Aspirin, Salbutamol",                                procedures:"None",                                        doctor:"Dr. Suresh Patel", doctor_id:"D204", appointment:"2025-04-13", next_appointment:"2025-07-08", lab:"CBC: Hb 12.3 g/dL | Blood Glucose: 177 mg/dL | Urine: Blood+" },
  { userId:"P311", name:"Manoj",    surname:"Singh",  email:"manoj.singh@email.com",    password:"pass311", age:"13", gender:"M", hospital:"Prima Diagnostic & Care",        hosp_address:"Kukatpally, Hyderabad",          hosp_phone:"+91-9395310485", disease:"Hypothyroidism",         status:"Discharged",      medicines:"Atorvastatin, Enoxaparin, Losartan",                 procedures:"MRI Brain, Hemodialysis",                     doctor:"Dr. Neha Sharma",  doctor_id:"D202", appointment:"2025-11-14", next_appointment:"2025-12-08", lab:"CBC: Hb 11.5 g/dL | Blood Glucose: 103 mg/dL | Urine: Blood+" },
  { userId:"P312", name:"Sanjay",   surname:"Reddy",  email:"sanjay.reddy2@email.com",  password:"pass312", age:"15", gender:"M", hospital:"Prima Diagnostic & Care",        hosp_address:"Kukatpally, Hyderabad",          hosp_phone:"+91-9395310485", disease:"Gastritis",              status:"Discharged",      medicines:"Aspirin, Clopidogrel, Paracetamol, Amoxicillin",     procedures:"Dialysis Session, MRI Brain",                 doctor:"Dr. Kiran Rao",    doctor_id:"D203", appointment:"2024-05-13", next_appointment:"2024-07-29", lab:"CBC: Hb 9.9 g/dL | Blood Glucose: 224 mg/dL | Urine: Pus Cells+" },
  { userId:"P313", name:"Manoj",    surname:"Singh",  email:"manoj.singh2@email.com",   password:"pass313", age:"72", gender:"M", hospital:"Green Valley General Hospital",   hosp_address:"Opp. Central Park, Hyderabad",   hosp_phone:"+91-9786579303", disease:"Chronic Kidney Disease", status:"Admitted",       medicines:"Salbutamol, Atorvastatin",                           procedures:"None",                                        doctor:"Dr. Suresh Patel", doctor_id:"D204", appointment:"2025-01-01", next_appointment:"2025-02-22", lab:"CBC: Hb 14.6 g/dL | Blood Glucose: 246 mg/dL | Urine: Pus Cells+" },
  { userId:"P314", name:"Priya",    surname:"Reddy",  email:"priya.reddy2@email.com",   password:"pass314", age:"53", gender:"Other", hospital:"CityCare Medical Centre",    hosp_address:"MG Road, Secunderabad",          hosp_phone:"+91-9219540831", disease:"Anemia",                 status:"Discharged",      medicines:"Furosemide, Salbutamol, Prednisone",                 procedures:"Tracheostomy, CT Scan",                       doctor:"Dr. Ravi Kumar",   doctor_id:"D201", appointment:"2024-04-20", next_appointment:"2024-05-25", lab:"CBC: Hb 14.1 g/dL | Blood Glucose: 274 mg/dL | Urine: Pus Cells+" },
  { userId:"P315", name:"Priya",    surname:"Reddy",  email:"priya.reddy3@email.com",   password:"pass315", age:"59", gender:"F", hospital:"Lotus MultiSpeciality Hospital", hosp_address:"Banjara Hills, Hyderabad",        hosp_phone:"+91-9126855092", disease:"Depression",             status:"Discharged",      medicines:"Furosemide",                                         procedures:"Endoscopy",                                   doctor:"Dr. Ravi Kumar",   doctor_id:"D201", appointment:"2025-11-26", next_appointment:"2026-01-05", lab:"CBC: Hb 9.6 g/dL | Blood Glucose: 238 mg/dL | Urine: Pus Cells+" },
  { userId:"P316", name:"Neha",     surname:"Kapoor", email:"neha.kapoor@email.com",    password:"pass316", age:"75", gender:"F", hospital:"Green Valley General Hospital",   hosp_address:"Opp. Central Park, Hyderabad",   hosp_phone:"+91-9786579303", disease:"Asthma",                 status:"Admitted",        medicines:"Prednisone, Levothyroxine, Metformin, Aspirin",      procedures:"None",                                        doctor:"Dr. Neha Sharma",  doctor_id:"D202", appointment:"2025-06-16", next_appointment:"2025-07-01", lab:"CBC: Hb 12.2 g/dL | Blood Glucose: 158 mg/dL | Urine: Blood+" },
  { userId:"P317", name:"Priya",    surname:"Reddy",  email:"priya.reddy4@email.com",   password:"pass317", age:"80", gender:"F", hospital:"Green Valley General Hospital",   hosp_address:"Opp. Central Park, Hyderabad",   hosp_phone:"+91-9786579303", disease:"Osteoarthritis",         status:"Under Treatment", medicines:"Metformin, Salbutamol",                              procedures:"Dialysis Session, Laparoscopic Cholecystectomy", doctor:"Dr. Kiran Rao",    doctor_id:"D203", appointment:"2024-11-04", next_appointment:"2024-12-07", lab:"CBC: Hb 11.5 g/dL | Blood Glucose: 240 mg/dL | Urine: Protein+" },
  { userId:"P318", name:"Meera",    surname:"Patel",  email:"meera.patel@email.com",    password:"pass318", age:"75", gender:"Other", hospital:"Lotus MultiSpeciality Hospital", hosp_address:"Banjara Hills, Hyderabad",     hosp_phone:"+91-9126855092", disease:"Otitis Media",           status:"Follow-up",       medicines:"Aspirin",                                            procedures:"Laparoscopic Cholecystectomy",                 doctor:"Dr. Asha Reddy",   doctor_id:"D200", appointment:"2024-08-28", next_appointment:"2024-09-22", lab:"CBC: Hb 11.1 g/dL | Blood Glucose: 242 mg/dL | Urine: Pus Cells+" },
  { userId:"P319", name:"Manoj",    surname:"Singh",  email:"manoj.singh3@email.com",   password:"pass319", age:"6",  gender:"M", hospital:"RiverSide Healthcare",            hosp_address:"Hitech City, Hyderabad",         hosp_phone:"+91-9896233790", disease:"Sepsis",                 status:"Admitted",        medicines:"Atorvastatin, Ceftriaxone",                          procedures:"Appendectomy, Coronary Angiography",           doctor:"Dr. Kiran Rao",    doctor_id:"D203", appointment:"2025-12-13", next_appointment:"2026-01-04", lab:"CBC: Hb 11.2 g/dL | Blood Glucose: 296 mg/dL | Urine: Pus Cells+" },
]);
console.log("✅ Patients seeded");

await client.close();
console.log("✅ Database seeded successfully!");
console.log("\nLogin credentials:");
console.log("  Patients: P300–P319 | password: pass300 to pass319");
console.log("  Doctors:  D200–D204 | password: pass200! to pass204!");
console.log("  Admin:    admin001  | password: admin123");
